all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh

webservers:
  hosts:
    main:
      ansible_host: "{{ PROD_SERVER_IP }}"
      ansible_user: "{{ SSH_USER }}"