- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install apt packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
  - name: Add docker gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add docker repository to apt
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: Install docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
  - name: Add user to docker group
    user:
      name: "{{ SSH_USER }}"
      group: "docker"
      append: yes
  - name: Install docker-compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: "u+x,g+x"
  - name: Install python docker/docker-compose
    pip:
      name:
          - docker
          - docker-compose